services:
  web:
    container_name: llm_honeypot_dashboard
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      - LOG_DIRECTORY=/data/cowrie/logs
      - STATS_FILE=/data/stats/honeypot_stats.json
      - FTP_LOG_FILE=/data/ftp/ftp_commands.json
      - DB_LOG_FILE=/data/db/general.log
      - API_LOG_FILE=/data/api/requests.json
      - DNS_LOG_FILE=/data/dns/dns_queries.json
      - WEBSERVER_LOG_FILE=/data/webserver/logs.json
    volumes:
      - /home/e2506292/cowrie/var/log/cowrie:/data/cowrie/logs:ro
      - /home/e2506292/LLM-honeypot/ftp_server/logs:/data/ftp:ro
      - /home/e2506292/db-server-logs:/data/db:ro
      - /home/e2506292/LLM-honeypot/api_server/logs:/data/api:ro
      - /home/e2506292/LLM-honeypot/dns_honeypot/dns_queries.json:/data/dns/dns_queries.json:ro
      - /home/e2506292/webserver-host-logs:/data/webserver:ro
      - /var/lib/docker/vol/_data:/data/stats
      - /var/www/honeypot:/www
    ports:
      - "127.0.0.1:8000:8000"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    develop:
      watch:
        - action: rebuild
          path: ./web

  webserver:
    container_name: web_server
    build:
      context: ./webserver
      dockerfile: Dockerfile
    environment:
      - LOG_FILE_PATH=logs/logs.json
      - PORT=8081
    volumes:
      - /home/e2506292/webserver-host-logs:/app/logs
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

  db_server:
    container_name: db_server
    build:
      context: ./db_server
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=test123AWay
    volumes:
      - db_data:/var/lib/mysql
      - /home/e2506292/db-server-logs:/var/log/mysql
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  stats_data:
    driver: local
  cowrie_logs:
    driver: local
  web_data:
    driver: local
  db_data:
    driver: local
